# Generated by Django 3.2 on 2023-03-16 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sys_user',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('mobile', models.IntegerField(blank=True, verbose_name='手机号码')),
                ('create_time', models.DateTimeField(verbose_name='创建时间')),
            ],
        ),
        migrations.CreateModel(
            name='Sys_user_token',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.FileField(max_length=255, upload_to='')),
                ('expire_time', models.DateField(verbose_name='过期时间')),
                ('update_time', models.DateField(verbose_name='更新时间')),
            ],
        ),
    ]
