# Generated by Django 3.2 on 2023-03-16 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user',
            name='mobile',
            field=models.IntegerField(verbose_name='手机号码'),
        ),
    ]
