# Generated by Django 3.2 on 2023-03-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_alter_sys_user_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='mobile',
            field=models.IntegerField(blank=True, null=True, verbose_name='手机号码'),
        ),
    ]
