# Generated by Django 3.2 on 2023-03-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_auto_20230316_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user_token',
            name='expire_time',
            field=models.DateTimeField(verbose_name='过期时间'),
        ),
        migrations.AlterField(
            model_name='sys_user_token',
            name='update_time',
            field=models.DateTimeField(verbose_name='更新时间'),
        ),
    ]
