# Generated by Django 3.2 on 2023-03-26 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['stockId']},
        ),
    ]
