# Generated by Django 3.2 on 2023-03-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_alter_stock_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShStock',
            fields=[
                ('shstockId', models.BigAutoField(primary_key=True, serialize=False)),
                ('INDEX_ABBR', models.CharField(blank=True, max_length=255, null=True, verbose_name='指数名称')),
                ('TOTAL_VALUE', models.FloatField(blank=True, null=True, verbose_name='')),
                ('AVG_PRICE', models.FloatField(blank=True, null=True, verbose_name='')),
                ('TRADE_AMT', models.FloatField(blank=True, null=True, verbose_name='成交额(亿元)')),
                ('VALUE_RATIO', models.FloatField(blank=True, null=True, verbose_name='')),
                ('INDEX_CODE', models.CharField(blank=True, max_length=255, null=True, verbose_name='指数代码')),
                ('CLOSE_POINT', models.FloatField(blank=True, null=True, verbose_name='收盘')),
                ('KIND_NUM', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('TRADE_DATE', models.CharField(blank=True, max_length=255, null=True, verbose_name='追踪时间')),
                ('RANK', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('PE_RATIO', models.FloatField(blank=True, null=True, verbose_name='静态市盈率')),
                ('AVG_VOL', models.FloatField(blank=True, null=True, verbose_name='平均股本(亿股)')),
            ],
        ),
    ]
