# Generated by Django 3.2 on 2023-03-26 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0010_shstock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shstock',
            name='AVG_PRICE',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shstock',
            name='AVG_VOL',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='平均股本(亿股)'),
        ),
        migrations.AlterField(
            model_name='shstock',
            name='CLOSE_POINT',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='收盘'),
        ),
        migrations.AlterField(
            model_name='shstock',
            name='PE_RATIO',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='静态市盈率'),
        ),
        migrations.AlterField(
            model_name='shstock',
            name='TOTAL_VALUE',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='shstock',
            name='TRADE_AMT',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='成交额(亿元)'),
        ),
        migrations.AlterField(
            model_name='shstock',
            name='VALUE_RATIO',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name=''),
        ),
    ]
