# Generated by Django 3.2 on 2023-04-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0012_stockbid'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('newsId', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('createTime', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('thumbnail', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('pcUrl', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('source', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('mediaName', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
                ('sourceForm', models.CharField(blank=True, max_length=255, null=True, verbose_name='')),
            ],
        ),
    ]
