# Generated by Django 3.2 on 2023-04-02 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='sourceForm',
            new_name='sourceFrom',
        ),
    ]
