# Generated by Django 3.2 on 2023-04-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_delete_singletimestock'),
    ]

    operations = [
        migrations.AddField(
            model_name='sys_user',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='居住地'),
        ),
        migrations.AddField(
            model_name='sys_user',
            name='gender',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='性别'),
        ),
        migrations.AddField(
            model_name='sys_user',
            name='info',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='个人简介'),
        ),
    ]
