# Generated by Django 3.2 on 2023-04-04 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_auto_20230404_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sys_user',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='个人简介'),
        ),
        migrations.AlterField(
            model_name='sys_user',
            name='mobile',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='手机号码'),
        ),
    ]
